### ISSUE TITLE
RR and BG2 FIxpack component 111 [Bard Song Fixes]

### ISSUE THREAD

**Issue by TotoR115** [FredrikLindgren/rr#8]
To have both (BG2 FIxpack component 111 [Bard Song Fixes] and RR) working together, there is some adjustment to make to RR Blade Kit : RR Blade song have to replace modification done by BG2 fixpack, and Line 660 need to be updated and condition to check BG2fixpack is needed. Line 660:

- LPF set_clab_2da_entries INT_VAR f_MinLevel = 1  f_MaxLevel = 1 STR_VAR f_Entry = AP_RR#BBL01 END

Could/need to be replaced, in case of BG2 fixpack, by, for example :

- SET_2DA_ENTRY 3 1 3 "AP_RR#BBL01"

**Comment by FredrikLindgren** [comment]
Thanks for the report. This has been fixed in c5285dea21eab896841a1b53b46d833cc795267d.

**Comment by TotoR115** [comment]
it is the same for the true calss bard. 
line 625 could be added :
  PATCH_IF INDEX_BUFFER (CASE_INSENSITIVE EXACT_MATCH AP_FJBLADE) >= 0 BEGIN // Swap BG2 Fixpack fix with RR song
    REPLACE_TEXTUALLY "AP_fjbard" "AP_RR#BDF01"
  END ELSE BEGIN 
    LPF set_clab_2da_entries
